# ---------------------------------------------------------------------------
# Trivadis AG, Infrastructure Managed Services
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# ---------------------------------------------------------------------------
# Name.......: Vagrantfile
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2019.05.09
# Revision...:  
# Purpose....: Vagrant file to setup and configure ad.trivadislabs.com
# Notes......: 
# Reference..: https://github.com/rgl/windows-domain-controller-vagrant
# License....: Licensed under the Universal Permissive License v 1.0 as 
#              shown at http://oss.oracle.com/licenses/upl.
# ---------------------------------------------------------------------------
# Modified...:
# see git revision history for more information on changes/updates
# ---------------------------------------------------------------------------
require 'yaml'

# install missing vagrant plugin
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

# - Configuration -----------------------------------------------------------
params              = YAML.load_file '../common/config/vagrant.yml'

# shared configuration
var_default_password= params['common']['default_password']
var_domain_name     = params['common']['domain_name']
var_gateway_address = params['common']['gateway_address']
var_public_dns1     = params['common']['public_dns1']
var_public_dns2     = params['common']['public_dns2']
var_dns             = params['common']['dns']

# ad box configuration
var_box             = params['ol7db122']['box']
var_box_url         = params['ol7db122']['box_url']
var_vm_name         = params['ol7db122']['vm_name']
var_host_fqdn       = var_vm_name + "." + var_domain_name
var_mem_size        = params['ol7db122']['mem_size']
var_cpus            = params['ol7db122']['cpus']
var_public_ip       = params['ol7db122']['public_ip']

# - End of Configuration ----------------------------------------------------

Vagrant.configure("2") do |config|
# - Domain controller -------------------------------------------------------
  config.vm.define var_vm_name do |cfg|
    cfg.vm.box      = var_box
    cfg.vm.box_url  = var_box_url
    cfg.vm.define   var_host_fqdn
    cfg.vm.hostname = var_vm_name

    # Share an additional common folder to the guest VM
    cfg.vm.synced_folder "../common", "/vagrant_common"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.

    # Oracle port forwarding
    cfg.vm.network :forwarded_port, guest: 22,   host: 11022
    cfg.vm.network :forwarded_port, guest: 1521, host: 11521
    cfg.vm.network :forwarded_port, guest: 5500, host: 11500
    cfg.vm.network :private_network, ip: var_public_ip
  
    cfg.vm.box_check_update = false
    # change memory size, cpus etc
    cfg.vm.provider "virtualbox" do |v|
      v.memory    = var_mem_size
      v.cpus      = var_cpus
      v.name      = var_host_fqdn
    end

    # Provision everything on the first run 
    # start part 1 of the setup
    cfg.vm.provision "shell", path: "../common/scripts/01_common_setup_os_db.sh"

    # reload the VM
    cfg.vm.provision :reload
    # start part 2 of the setup
    # install DB binaries
    cfg.vm.provision "shell", path: "scripts/10_install_binaries.sh"
    # install Trivadis BasEnv
    cfg.vm.provision "shell", path: "../common/scripts/11_install_basenv.sh"
    # configure TNSADMIN
    cfg.vm.provision "shell", path: "../common/scripts/12_config_tnsadmin.sh"
    # create databases
    cfg.vm.provision "shell", path: "../common/scripts/20_create_databases.sh"
  end
end
# --- EOF -------------------------------------------------------------------